let items = [
    {
        id: "001",
        item_image: "images/PIMAGES/ERGDR18KU.jpg",
        item_name: "Reliance Jewels 22 Kt Gold Round Designed Hoops Earrings",
        current_price: 8840,
        orginal_price: 13000,
        discount_price: 32,
    },
    {
        id: "002",
        item_image: "images/PIMAGES/PDTDR17P1.jpg",
        item_name: "Reliance Jewels 22 Kt Gold Heart Pendant",
        current_price: 6120,
        orginal_price: 9000,
        discount_price: 32,
    },
    {
        id: "003",
        item_image: "images/PIMAGES/NOSDR18CO.jpg",
        item_name: "Reliance Jewels 14 Kt Gold & Diamond Nose Pin",
        current_price: 3400,
        orginal_price: 5000,
        discount_price: 32,
    },
    {
        id: "004",
        item_image: "images/PIMAGES/CHNRG15AC.jpg",
        item_name: "Reliance Jewels 22 Kt Gold Box Style Chain",
        current_price: 20400,
        orginal_price: 30000,
        discount_price: 32,
    },
    {
        id: "005",
        item_image: "images/PIMAGES/BLTDH17PT.jpg",
        item_name: "Reliance Jewels 14 Kt Gold & Diamond Openable Bracelet",
        current_price: 17000,
        orginal_price: 25000,
        discount_price: 32,
    },
    {
        id: "006",
        item_image: "images/PIMAGES/RNGDF17GD.jpg",
        item_name: "Reliance Jewels 22 Kt Gold Asymmetric Designed Pendant",
        current_price: 12852,
        orginal_price: 18900,
        discount_price: 32,
    }, {
        id: "007",
        item_image: "images/PIMAGES/RNGDG17VW.jpg",
        item_name: "Reliance Jewels 22 Kt Gold Round Designed Hoops Kada",
        current_price: 8840,
        orginal_price: 13000,
        discount_price: 32,
    },
// ======================================
    {
        id: "008",
        item_image: "images/PIMAGES/ERGDR18KU.jpg",
        item_name: "Reliance Jewels 22 Kt Gold Round Designed Hoops Earrings",
        current_price: 8840,
        orginal_price: 13000,
        discount_price: 32,
    },
    {
        id: "009",
        item_image: "images/PIMAGES/PDTDR17P1.jpg",
        item_name: "Reliance Jewels 22 Kt Gold Heart Pendant",
        current_price: 6120,
        orginal_price: 9000,
        discount_price: 32,
    },
    {
        id: "010",
        item_image: "images/PIMAGES/NOSDR18CO.jpg",
        item_name: "Reliance Jewels 14 Kt Gold & Diamond Nose Pin",
        current_price: 3400,
        orginal_price: 5000,
        discount_price: 32,
    },

]